# Generated by Django 4.2.7 on 2023-11-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_products', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField(max_length=255)),
                ('fabricante', models.TextField(max_length=255)),
                ('genero', models.TextField(max_length=255)),
                ('modelo', models.TextField(max_length=255)),
                ('cor', models.TextField(max_length=255)),
                ('tamanho', models.IntegerField()),
                ('description', models.TextField(max_length=255, null=True)),
                ('ncm', models.IntegerField()),
                ('gtin', models.BigIntegerField()),
            ],
        ),
    ]
