# Generated by Django 4.2.7 on 2023-11-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ncm',
            field=models.TextField(max_length=50),
        ),
    ]
