# Generated by Django 4.2.7 on 2023-11-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0004_rename_description_products_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='QtdProduto',
            fields=[
                ('id_qtdproduto', models.AutoField(primary_key=True, serialize=False)),
                ('qtdproduto', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='cor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='fabricante',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='genero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='ncm',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='qtdproduto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_products.qtdproduto'),
        ),
    ]
