# Generated by Django 4.2.7 on 2023-11-10 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0005_qtdproduto_alter_products_cor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='id_products',
            new_name='id_product',
        ),
        migrations.RemoveField(
            model_name='products',
            name='qtdproduto',
        ),
        migrations.AddField(
            model_name='qtdproduto',
            name='id_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_products.products'),
        ),
    ]
