# Generated by Django 4.2.7 on 2023-11-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0006_rename_id_products_products_id_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtdproduto',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.products'),
        ),
    ]
