# Generated by Django 4.2.5 on 2023-11-12 04:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_products', '0008_products_qtdproduto_delete_qtdproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransactions',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.products')),
            ],
        ),
    ]
