# Generated by Django 4.2.7 on 2023-11-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_rename_gtin_products_gtin_rename_ncm_products_ncm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
